### ISSUE TITLE
Themes folder not created by generator in src

### ISSUE THREAD

**Issue by nicola** [mozbrick/generator-brick#20]
```
...
[17:58:32] Finished 'styles' after 131 ms
[17:58:32] Starting 'vulcanize'...

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/mozilla/Proj/mozilla/brick/brick-button/src/themes/default/default.css'
  at Object.fs.openSync (fs.js:432:18)
  at Object.fs.readFileSync (fs.js:289:15)
  at readFile (/Users/mozilla/Proj/mozilla/brick/brick-button/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:54:20)
  at Object.<anonymous> (/Users/mozilla/Proj/mozilla/brick/brick-button/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:66:81)
  at [object Object].exports.each (/Users/mozilla/Proj/mozilla/brick/brick-button/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/cheerio/lib/api/traversing.js:267:24)
  at inlineSheets (/Users/mozilla/Proj/mozilla/brick/brick-button/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:60:31)
  at Object.handleMainDocument [as processDocument] (/Users/mozilla/Proj/mozilla/brick/brick-button/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:174:5)
  at /Users/mozilla/Proj/mozilla/brick/brick-button/node_modules/gulp-vulcanize/index.js:39:14
  at /Users/mozilla/Proj/mozilla/brick/brick-button/node_modules/gulp-vulcanize/node_modules/mkdirp/index.js:29:20
  at Object.oncomplete (fs.js:107:15)
```

**Comment by nicola** [comment]
Fixed 272857cc5497711a4cc53e2705315fa78b71361b
